version: '3'

services:
  transformer-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    # Environment variables can be added here if needed
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s